# Note: Ensure you have created a virtual environment named 'mre_venv' in the project directory

# Activate venv and run Streamlit
run:
	source mre_venv/Scripts/activate && streamlit run main.py

# for Unix/MacOS users run the following command
run-unix:
	. mre_venv/bin/activate && streamlit run main.py